### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by UG-SEP** [Arsenic-ATG/Sudoku#6]
Hey @Arsenic-ATG it will be better if you add a LICENSE so others can also use it 
MIT LICENSE would be a great choice for it 
Thanks

**Comment by UG-SEP** [comment]
and thanks yaar do to seeing you that we can I also started learning qt 
If you have any suggestion please tell me

**Comment by Arsenic-ATG** [comment]
Yes, I would be adding a license after completing adition of core functionally of the software.

**Comment by UG-SEP** [comment]
well from where did you learn about qt and how many months spend you are using it

**Comment by Arsenic-ATG** [comment]
@UG-SEP although I started using Qt almost a year ago, I am not a very active user of it and quite often find myself scanning [their docs](https://doc.qt.io) when stuck while building projects like these. They have quite nicely written docs so I rarely find myself wandering somewhere else in search for answers.
